apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubewarden-extra-context-watcher
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways", "httproutes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubewarden-extra-context-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewarden-extra-context-watcher
subjects:
  - kind: ServiceAccount
    name: policy-server
    namespace: kubewarden
